---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: warcraft2/wordsmith-api
    newName: ghcr.io/warcraft2/wordsmith-api
    newTag: stable-20230717-6bc2d7b
  - name: warcraft2/wordsmith-web
    newName: ghcr.io/warcraft2/wordsmith-web
    newTag: stable-20230717-de7fbdf
  - name: db-schema
    files:
      - words.sql
